import os
import sys
from typing import List,Optional
from dotenv import load_dotenv
from operator import itemgetter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import BaseMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_community.vectorstores import FAISS
from utils.model_loader import ModelLoader
from exception.custom_exception import DocumentPortalException
from logger.custom_logger import CustomLogger
from prompt.prompt_library import PROMPT_REGISTRY
from model.models import PromptType




class ConversationRAG:
    def __init__(self,session_id:str,retriever=None):
        try:
            self.log=CustomLogger().get_logger(__name__)
            self.session_id=session_id
            self.llm=self._load_llm()
            self.contextualize_prompt=ChatPromptTemplate=PROMPT_REGISTRY[PromptType.CONTEXTUALIZE_QUESTION.value]
            self.qa_prompt=ChatPromptTemplate=PROMPT_REGISTRY[PromptType.QA.value]
            if retriever is None:
                raise ValueError("Retriever cannot be none")
            self.retriever=retriever
            self._build_lcel_chain()
            self.log.info("ConversationRAG initialized",session_id=self.session_id)


        except Exception as e:
            self.log.error("Error initializing ConversationRAG:",error=str(e))
            raise DocumentPortalException("Initialization error in ConversationRAG: ",sys)

        
    def load_retriever_from_faiss(self,index_path:str):
        """
        Load a Faiss vectorstore from disk and convert to retriever.
        """
        try:
            embeddings=ModelLoader().load_embeddings()
            if not os.path.isdir(index_path):
                raise FileNotFoundError(f"Faiss index directory not found: {index_path}")
            vectorstore=FAISS.load_local(
                index_path,
                embeddings,
                allow_dangerous_deserialization=True

            )
            self.retriever=vectorstore.as_retriever(search_type="similarity",search_kwargs={"k":5})
            self.log.info("Retriever loaded from Faiss index",index_path=index_path,session_id=self.session_id)
            self._build_lcel_chain()
            return self.retriever

            
        except Exception as e:
            self.log.error("Error loading retriever from Faiss:",error=str(e))
            raise DocumentPortalException("Loading error in ConversationRAG: ",sys)


    def invoke(self,user_input:str,chat_history:Optional[List[BaseMessage]]=None):
        """_summary_
        Args:
            user_input (str): _description_
            chat_history (Optional[List[BaseMessage]], optional): _description_. Defaults to None.

        """
        try:
            chat_history=chat_history or []
            payload={
                "input":user_input,
                "chat_history":chat_history 
            }
            answer=self.chain.invoke(payload)
            
            if not answer:
                self.log.warning("No answer generated by ConversationRAG",session_id=self.session_id,user_input=user_input)
                return "No Answer generated"
            self.log.info("chain invoked sucessfully",
                    session_id=self.session_id,
                    user_input=user_input,
                    answer_preview=answer[:150]
            )
            return answer
        except Exception as e:
            self.log.error("Error invoking ConversationRAG:",error=str(e))
            raise DocumentPortalException("Invocation error in ConversationRAG: ",sys)
    def _load_llm(self):
        try:
            llm=ModelLoader().load_llm()
            if not llm:
                raise ValueError("LLM could not be loaded")
            self.log.info("LLM loaded successfully",session_id=self.session_id)
            return llm
        except Exception as e:
            self.log.error("Error loading LLM:",error=str(e))
            raise DocumentPortalException("LLM loading error in ConversationRAG: ",sys) 
    @staticmethod
    def _format_docs(docs):
        return "\n\n".join(d.page_content for d in docs)
    def _build_lcel_chain(self):
        try:
            question_rewriter={
                {"input":itemgetter("input"),"chat_history":itemgetter("chat_history")} | self.contextualize_prompt | self.llm|StrOutputParser()    
            }
            retrieve_docs=question_rewriter | self.retriever | self._format_docs
            self.chain=(
                {
                    "context":retrieve_docs,
                    "input": itemgetter("input"),
                    "chat_history":itemgetter("chat_history"),


                }
                |self.qa_prompt
                |self.llm
                |StrOutputParser()

            )
        except Exception as e:
            self.log.error("Error building LCEL chain:",error=str(e))
            raise DocumentPortalException("LCEL Chain building error in ConversationRAG: ",sys) 

